/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HttpRequest {
  'url' : string,
  'method' : string,
  'body' : Uint8Array,
  'headers' : Array<[string, string]>,
}
export interface HttpResponse {
  'body' : Uint8Array,
  'headers' : Array<[string, string]>,
  'upgrade' : [] | [boolean],
  'status_code' : number,
}
export interface OAuthStartParams {
  'state' : string,
  'codeVerifier' : string,
  'authUrl' : string,
}
export type Result = { 'ok' : string } |
  { 'err' : string };
export interface TwitterStatus {
  'username' : [] | [string],
  'connected' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeOAuth' : ActorMethod<[string, string], Result>,
  'createBooking' : ActorMethod<
    [string, string, bigint, string, string],
    string
  >,
  'disconnectTwitter' : ActorMethod<[], undefined>,
  'forceSetAdmin' : ActorMethod<[Principal], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOAuthStartParams' : ActorMethod<[string], OAuthStartParams>,
  'getTwitterStatus' : ActorMethod<[], TwitterStatus>,
  'getXClientId' : ActorMethod<[], [] | [string]>,
  'http_request' : ActorMethod<[HttpRequest], HttpResponse>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerAdminUpdate' : ActorMethod<[], boolean>,
  'setXClientId' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];