/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const OAuthStartParams = IDL.Record({
  'state' : IDL.Text,
  'codeVerifier' : IDL.Text,
  'authUrl' : IDL.Text,
});
export const TwitterStatus = IDL.Record({
  'username' : IDL.Opt(IDL.Text),
  'connected' : IDL.Bool,
});
export const HttpRequest = IDL.Record({
  'url' : IDL.Text,
  'method' : IDL.Text,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
});
export const HttpResponse = IDL.Record({
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'upgrade' : IDL.Opt(IDL.Bool),
  'status_code' : IDL.Nat16,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeOAuth' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'createBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'disconnectTwitter' : IDL.Func([], [], []),
  'forceSetAdmin' : IDL.Func([IDL.Principal], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOAuthStartParams' : IDL.Func([IDL.Text], [OAuthStartParams], []),
  'getTwitterStatus' : IDL.Func([], [TwitterStatus], ['query']),
  'getXClientId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdminUpdate' : IDL.Func([], [IDL.Bool], []),
  'setXClientId' : IDL.Func([IDL.Text], [], []),
  'state' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const OAuthStartParams = IDL.Record({
    'state' : IDL.Text,
    'codeVerifier' : IDL.Text,
    'authUrl' : IDL.Text,
  });
  const TwitterStatus = IDL.Record({
    'username' : IDL.Opt(IDL.Text),
    'connected' : IDL.Bool,
  });
  const HttpRequest = IDL.Record({
    'url' : IDL.Text,
    'method' : IDL.Text,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  const HttpResponse = IDL.Record({
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'upgrade' : IDL.Opt(IDL.Bool),
    'status_code' : IDL.Nat16,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeOAuth' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'createBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'disconnectTwitter' : IDL.Func([], [], []),
    'forceSetAdmin' : IDL.Func([IDL.Principal], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOAuthStartParams' : IDL.Func([IDL.Text], [OAuthStartParams], []),
    'getTwitterStatus' : IDL.Func([], [TwitterStatus], ['query']),
    'getXClientId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdminUpdate' : IDL.Func([], [IDL.Bool], []),
    'setXClientId' : IDL.Func([IDL.Text], [], []),
    'state' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };